# Generated by Django 4.2 on 2025-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title (French)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fr', models.TextField(verbose_name='Description (French)')),
            ],
        ),
    ]
