# Generated by Django 4.2 on 2025-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='page_name',
            field=models.CharField(default='home', max_length=255, verbose_name='Page Name'),
        ),
    ]
